[rospy.client][INFO] 2017-06-16 11:01:35,786: init_node, name[/move_sandbox_items], pid[13908]
[xmlrpc][INFO] 2017-06-16 11:01:35,787: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-16 11:01:35,787: Started XML-RPC server [http://sandtray-hrilab:44792/]
[rospy.init][INFO] 2017-06-16 11:01:35,787: ROS Slave URI: [http://sandtray-hrilab:44792/]
[rospy.impl.masterslave][INFO] 2017-06-16 11:01:35,787: _ready: http://sandtray-hrilab:44792/
[xmlrpc][INFO] 2017-06-16 11:01:35,788: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2017-06-16 11:01:35,788: Registering with master node http://localhost:11311
[rospy.init][INFO] 2017-06-16 11:01:35,888: registered with master
[rospy.rosout][INFO] 2017-06-16 11:01:35,888: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-16 11:01:35,890: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-16 11:01:35,891: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-16 11:01:35,905: topic[/tf] adding connection to [http://sandtray-hrilab:33692/], count 0
[rospy.internal][INFO] 2017-06-16 11:01:35,908: topic[/tf] adding connection to [http://sandtray-hrilab:41021/], count 1
[rospy.internal][INFO] 2017-06-16 11:01:35,910: topic[/tf] adding connection to [http://sandtray-hrilab:43483/], count 2
[rospy.internal][INFO] 2017-06-16 11:01:35,912: topic[/tf] adding connection to [http://sandtray-hrilab:39164/], count 2
[rospy.internal][INFO] 2017-06-16 11:01:35,913: topic[/tf] adding connection to [http://sandtray-hrilab:40066/], count 3
[rospy.internal][INFO] 2017-06-16 11:01:36,097: topic[/poses] adding connection to [/sandtray], count 0
[rospy.internal][INFO] 2017-06-16 11:01:36,130: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2017-06-16 11:04:07,725: Unknown error initiating TCP/IP socket to sandtray-hrilab:53696 (http://sandtray-hrilab:41021/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-16 11:04:07,725: topic[/tf] removing connection to http://sandtray-hrilab:41021/
[rospy.internal][INFO] 2017-06-16 11:05:50,930: topic[/tf] adding connection to [http://sandtray-hrilab:37120/], count 4
[rospy.internal][INFO] 2017-06-16 11:05:51,932: topic[/tf] adding connection to [http://sandtray-hrilab:45775/], count 5
[rospy.internal][WARNING] 2017-06-16 11:11:04,647: Unknown error initiating TCP/IP socket to sandtray-hrilab:52078 (http://sandtray-hrilab:37120/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-16 11:11:04,647: topic[/tf] removing connection to http://sandtray-hrilab:37120/
[rospy.internal][WARNING] 2017-06-16 11:11:04,647: Unknown error initiating TCP/IP socket to sandtray-hrilab:43460 (http://sandtray-hrilab:45775/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-16 11:11:04,647: topic[/tf] removing connection to http://sandtray-hrilab:45775/
[rospy.internal][INFO] 2017-06-16 11:11:09,474: topic[/tf] adding connection to [http://sandtray-hrilab:44726/], count 4
[rospy.internal][INFO] 2017-06-16 11:11:10,475: topic[/tf] adding connection to [http://sandtray-hrilab:45510/], count 5
[rospy.internal][WARNING] 2017-06-16 11:47:49,985: Unknown error initiating TCP/IP socket to sandtray-hrilab:60859 (http://sandtray-hrilab:44726/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-16 11:47:49,985: topic[/tf] removing connection to http://sandtray-hrilab:44726/
[rospy.internal][WARNING] 2017-06-16 11:47:49,991: Unknown error initiating TCP/IP socket to sandtray-hrilab:39679 (http://sandtray-hrilab:45510/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 635, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 422, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-16 11:47:49,991: topic[/tf] removing connection to http://sandtray-hrilab:45510/
[rospy.core][INFO] 2017-06-16 11:47:55,266: signal_shutdown [signal-15]
[rospy.internal][WARNING] 2017-06-16 11:47:55,267: Unknown error initiating TCP/IP socket to sandtray-hrilab:36230 (http://sandtray-hrilab:43483/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-16 11:47:55,267: topic[/tf] removing connection to http://sandtray-hrilab:43483/
[rospy.internal][INFO] 2017-06-16 11:47:55,274: topic[/poses] removing connection to /sandtray
[rospy.internal][INFO] 2017-06-16 11:47:55,275: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-16 11:47:55,275: topic[/tf] removing connection to http://sandtray-hrilab:33692/
[rospy.internal][INFO] 2017-06-16 11:47:55,275: topic[/tf] removing connection to http://sandtray-hrilab:39164/
[rospy.internal][INFO] 2017-06-16 11:47:55,275: topic[/tf] removing connection to http://sandtray-hrilab:40066/
[rospy.impl.masterslave][INFO] 2017-06-16 11:47:55,275: signal-15
[rospy.core][INFO] 2017-06-16 11:47:55,351: signal_shutdown [signal-2]
[rospy.core][INFO] 2017-06-16 11:47:55,351: signal_shutdown [atexit]
