[rospy.client][INFO] 2017-06-27 10:59:47,260: init_node, name[/move_sandbox_items], pid[7369]
[xmlrpc][INFO] 2017-06-27 10:59:47,260: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-27 10:59:47,261: Started XML-RPC server [http://sandtray-hrilab:38690/]
[rospy.init][INFO] 2017-06-27 10:59:47,261: ROS Slave URI: [http://sandtray-hrilab:38690/]
[rospy.impl.masterslave][INFO] 2017-06-27 10:59:47,261: _ready: http://sandtray-hrilab:38690/
[rospy.registration][INFO] 2017-06-27 10:59:47,262: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2017-06-27 10:59:47,262: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-06-27 10:59:47,361: registered with master
[rospy.rosout][INFO] 2017-06-27 10:59:47,361: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-27 10:59:47,364: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-27 10:59:47,365: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-27 10:59:47,378: topic[/tf] adding connection to [http://sandtray-hrilab:39659/], count 0
[rospy.internal][INFO] 2017-06-27 10:59:47,382: topic[/tf] adding connection to [http://sandtray-hrilab:36058/], count 1
[rospy.internal][INFO] 2017-06-27 10:59:47,383: topic[/tf] adding connection to [http://sandtray-hrilab:39890/], count 1
[rospy.internal][INFO] 2017-06-27 10:59:47,383: topic[/tf] adding connection to [http://sandtray-hrilab:40171/], count 1
[rospy.internal][INFO] 2017-06-27 10:59:47,384: topic[/tf] adding connection to [http://sandtray-hrilab:41235/], count 3
[rospy.internal][INFO] 2017-06-27 10:59:47,503: topic[/poses] adding connection to [/sandtray], count 0
[rospy.internal][INFO] 2017-06-27 10:59:47,604: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][WARNING] 2017-06-27 11:01:33,714: Unknown error initiating TCP/IP socket to sandtray-hrilab:33892 (http://sandtray-hrilab:39890/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-27 11:01:33,714: topic[/tf] removing connection to http://sandtray-hrilab:39890/
[rospy.internal][INFO] 2017-06-27 11:01:34,607: topic[/tf] adding connection to [http://sandtray-hrilab:45710/], count 4
[rospy.internal][INFO] 2017-06-27 11:01:35,871: topic[/tf] adding connection to [http://sandtray-hrilab:37425/], count 5
[rospy.internal][WARNING] 2017-06-27 11:11:59,435: Unknown error initiating TCP/IP socket to sandtray-hrilab:54085 (http://sandtray-hrilab:45710/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-27 11:11:59,436: topic[/tf] removing connection to http://sandtray-hrilab:45710/
[rospy.internal][WARNING] 2017-06-27 11:11:59,438: Unknown error initiating TCP/IP socket to sandtray-hrilab:47643 (http://sandtray-hrilab:37425/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-27 11:11:59,439: topic[/tf] removing connection to http://sandtray-hrilab:37425/
[rospy.internal][INFO] 2017-06-27 11:12:10,940: topic[/tf] adding connection to [http://sandtray-hrilab:40671/], count 4
[rospy.internal][INFO] 2017-06-27 11:12:11,941: topic[/tf] adding connection to [http://sandtray-hrilab:38934/], count 5
[rospy.internal][WARNING] 2017-06-27 11:43:38,777: Unknown error initiating TCP/IP socket to sandtray-hrilab:54255 (http://sandtray-hrilab:40671/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-27 11:43:38,778: topic[/tf] removing connection to http://sandtray-hrilab:40671/
[rospy.internal][WARNING] 2017-06-27 11:43:38,783: Unknown error initiating TCP/IP socket to sandtray-hrilab:60943 (http://sandtray-hrilab:38934/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 556, in connect
    self.write_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 635, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 422, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-27 11:43:38,783: topic[/tf] removing connection to http://sandtray-hrilab:38934/
[rospy.core][INFO] 2017-06-27 11:45:59,748: signal_shutdown [signal-15]
[rospy.internal][WARNING] 2017-06-27 11:45:59,750: Unknown error initiating TCP/IP socket to sandtray-hrilab:56668 (http://sandtray-hrilab:41235/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-27 11:45:59,751: topic[/tf] removing connection to http://sandtray-hrilab:41235/
[rospy.internal][INFO] 2017-06-27 11:45:59,756: topic[/poses] removing connection to /sandtray
[rospy.internal][INFO] 2017-06-27 11:45:59,757: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-27 11:45:59,757: topic[/tf] removing connection to http://sandtray-hrilab:39659/
[rospy.internal][WARNING] 2017-06-27 11:45:59,757: Unknown error initiating TCP/IP socket to sandtray-hrilab:57075 (http://sandtray-hrilab:39659/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2017-06-27 11:45:59,757: Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 838, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2017-06-27 11:45:59,758: topic[/tf] removing connection to http://sandtray-hrilab:36058/
[rospy.internal][INFO] 2017-06-27 11:45:59,758: topic[/tf] removing connection to http://sandtray-hrilab:40171/
[rospy.impl.masterslave][INFO] 2017-06-27 11:45:59,758: signal-15
[rospy.core][INFO] 2017-06-27 11:45:59,776: signal_shutdown [signal-2]
[rospy.core][INFO] 2017-06-27 11:45:59,809: signal_shutdown [atexit]
